# Generated by Django 3.0.4 on 2020-04-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peckn_app', '0002_auto_20200402_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerContact',
            new_name='Contact',
        ),
    ]
